services:
  api:
    image: api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_DSN: ${DB_DSN}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_ENV: ${SERVER_ENV}
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: polls
    volumes:
      - polls-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DOMAIN: ${DOMAIN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  polls-db-data:
  caddy_data:
  caddy_config:
